Repository php-fig/fig-standards, pull requests merged in 2019-02, with the labels that each got.

#849 the param of groupHug should be from type Huggable[]
  proposed/psr-8-hug/psr-8-hug.md
Labels: PSR-8: Huggable

#1147 Update PSR-14 status to Review
  index.md
Labels: PSR-14: Events

#1148 PSR-12: removed unclear statement about unary operators
  proposed/extended-coding-style-guide.md
Labels: PSR-1 + PSR-2 + PSR-12: Coding Style

#1149 PSR-14 edits
  proposed/event-dispatcher-meta.md
  proposed/event-dispatcher.md
Labels: PSR-14: Events

#1151 Fix CC terms
  personnel.md
Labels: Typos and Errata
