Repository php-fig/fig-standards, pull requests merged in 2022-01, with the labels that each got.

#1263 Remove Drupal
  personnel.md
Labels: Internal: Bylaw or Admin Change, WIP

#1265 Fix examples in `PSR-7-http-message-meta.md`
  accepted/PSR-7-http-message-meta.md
Labels: PSR-7: HTTP Message, PSR-18: HTTP Client

#1267 Update personnel list after January 2022 elections
  personnel.md
Labels: Internal: Bylaw or Admin Change
